// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9IAgRD_e-8RelYpf1vzZg0fy5AGbJC4',
    appId: '1:290112950821:web:6022c37b09f844eaaa25cc',
    messagingSenderId: '290112950821',
    projectId: 'vibewrite-2eaa0',
    authDomain: 'vibewrite-2eaa0.firebaseapp.com',
    storageBucket: 'vibewrite-2eaa0.firebasestorage.app',
    measurementId: 'G-58F3L3VGWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNl853TtOI9o1nw_FaKCHO895vG8k-JI',
    appId: '1:290112950821:android:9a69c1c20fcbca99aa25cc',
    messagingSenderId: '290112950821',
    projectId: 'vibewrite-2eaa0',
    storageBucket: 'vibewrite-2eaa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQuTThtv8rXqEFNWQiFPe_Xog7vI-KDvs',
    appId: '1:290112950821:ios:0ad9a371df3bc9e2aa25cc',
    messagingSenderId: '290112950821',
    projectId: 'vibewrite-2eaa0',
    storageBucket: 'vibewrite-2eaa0.firebasestorage.app',
    iosBundleId: 'com.example.vibewriteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQuTThtv8rXqEFNWQiFPe_Xog7vI-KDvs',
    appId: '1:290112950821:ios:0ad9a371df3bc9e2aa25cc',
    messagingSenderId: '290112950821',
    projectId: 'vibewrite-2eaa0',
    storageBucket: 'vibewrite-2eaa0.firebasestorage.app',
    iosBundleId: 'com.example.vibewriteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU9IAgRD_e-8RelYpf1vzZg0fy5AGbJC4',
    appId: '1:290112950821:web:2406d0da168b6264aa25cc',
    messagingSenderId: '290112950821',
    projectId: 'vibewrite-2eaa0',
    authDomain: 'vibewrite-2eaa0.firebaseapp.com',
    storageBucket: 'vibewrite-2eaa0.firebasestorage.app',
    measurementId: 'G-P1W5H86PQG',
  );

}